repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        args: ["--fix"]
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        types: [python]