[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "expressive-tts-arena"
version = "0.1.0"
dependencies = [
  "gradio>=5.13.1",
  "python-dotenv>=1.0.1",
  "anthropic>=0.45.2",
  "elevenlabs>=1.50.6",
  "tenacity>=9.0.0",
  "requests>=2.32.3"
]

[project.optional-dependencies]
dev = [
  "black==25.1.0",
  "ruff==0.9.3",
  "pytest>=7.0",
  "pre-commit>=3.2.0",
  "mypy>=1.5"
]